# Generated by Django 5.1.2 on 2024-11-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0004_profile_image_alter_profile_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_image',
            field=models.ImageField(blank=True, null=True, upload_to='tweet_images'),
        ),
    ]
