# Generated by Django 5.1.2 on 2024-12-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0006_savedposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_image',
        ),
        migrations.AddField(
            model_name='tweet',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='tweet_images'),
        ),
    ]
