# Generated by Django 5.1.2 on 2024-12-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0009_verifyotp_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyotp',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
