# Generated by Django 5.1.2 on 2024-12-12 12:53

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0010_alter_verifyotp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter phone number with country code.', max_length=128, null=True, region=None),
        ),
    ]
